project:
  type: book
  output-dir: docs
book:
  title: "stochacalculus"
  author: "David Peña Peralta"
  date: "25/11/2023"
  chapters:
    - index.qmd
    - Tarea1.qmd
    - Tarea2.qmd
    - Tarea3.qmd
    - Tarea4.qmd
    - Tarea5.qmd
    - Tarea6.qmd
    - Tarea7.qmd
    - Tarea8.qmd
    - Tarea9.qmd
    - Tarea10.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



