project:
  type: book
  output-dir: docs
book:
  title: "stochacalculus"
  author: "David Peña Peralta"
  date: "25/11/2023"
  chapters:
    - index.qmd
    - Tarea1.ipynb
    - Tarea2.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



