project:
  type: book
  output-dir: docs

book:
  title: "mma_hws"
  author: "Norah Jones"
  date: "1/12/2023"
  chapters:
    - index.qmd
    - aux_codes.qmd
    - Tarea1.qmd
    - Tarea2.qmd
    - Tarea3.qmd
    - Tarea4.qmd
    - Tarea5.qmd
    - Tarea6.qmd
    - Tarea7.qmd
    - Tarea8.qmd
    - Tarea9.qmd
    - Tarea10.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



