# Tarea 10


::: {#exr-1}

Considere la ecuación diferencial estocástica lineal con ruido multiplicativo.
$$
\mathrm{d}Y\left(t\right)=\left(\mu+\dfrac{1}{2}\sigma^{2}\right)Y\left(t\right)\mathrm{d}t+\sigma\mathrm{d}W\left(t\right)
$$

Aplicando la Fórmula de Ito a la función 

$$
u\left(t,x\right)=y_{0}\exp\left(\mu t+\sigma x\right).
$$

Muestre que 

$$
Y\left(t\right)=Y\left(0\right)\exp\left(\mu t+\sigma W\left(t\right)\right),
$$

resuelve la ecuación diferencial.

:::

Considere 
$$
u\left(t,x\right)=y_{0}\exp\left(\mu t+\sigma x\right)
$$

Ahora 
\begin{align*}
\partial_{t}u & =\mu u\\
\partial_{x}u & =\sigma u\\
\partial_{xx} & =\sigma^{2}u
\end{align*}

Usando además que. 

$$
\mathrm{d}S_{t}=\mathrm{d}W_{t}
$$

Entonces 
\begin{align*}
\mathrm{d}u\left(t,Y_{t}\right) & =\mu u\mathrm{d}t+\sigma u\mathrm{d}Y_{t}+\dfrac{1}{2}\sigma^{2}u\left(\mathrm{d}Y_{t}\right)^{2}\\
 & =\mu u\mathrm{d}t+\sigma u\mathrm{d}W_{t}+\dfrac{1}{2}\sigma^{2}u\mathrm{d}t\\
 & =\left(\mu+\dfrac{1}{2}\sigma^{2}\right)u\mathrm{dt+\sigma u\mathrm{d}}W_{t}
\end{align*}

Entonces 
\begin{align*}
Y_{t} & =u\left(t,Y_{t}\right)\\
 & =Y\left(0\right)\exp\left(\mu t+\sigma W_{t}\right)
\end{align*}

En general 
$$
\mathrm{d}X_{t}=\mu X_{t}\mathrm{d}t+\sigma X_{t}\mathrm{d}W_{t}
$$





::: {#exr-1}

Use el hecho anterior, confirma que 

$$
Y\left(t\right)=Y\left(0\right)\exp\left(\left(\mu-\dfrac{1}{2}\sigma^{2}\right)t+\sigma W\left(t\right)\right),
$$

resuelve, 

$$
\mathrm{d}Y\left(t\right)=\mu Y\left(t\right)\mathrm{d}t+\sigma Y\left(t\right)\mathrm{d}W\left(t\right)
$$

:::

Considere 
$$
u\left(t,x\right)=y_{0}\exp\left(q_{1}t+q_{2}x\right)
$$

Ahora 
\begin{align*}
\partial_{t}u & =q_{1}u\\
\partial_{x}u & =q_{2}u\\
\partial_{xx} & =q_{2}^{2}u
\end{align*}

Usando además que. 

$$
\mathrm{d}S_{t}=\mathrm{d}W_{t}
$$

Entonces 
\begin{align*}
\mathrm{d}u\left(t,Y_{t}\right) & =q_{1}u\mathrm{d}t+q_{2}u\mathrm{d}Y_{t}+\dfrac{1}{2}q_{2}^{2}u\left(\mathrm{d}Y_{t}\right)^{2}\\
 & =q_{1}u\mathrm{d}t+q_{2}u\mathrm{d}W_{t}+\dfrac{1}{2}q_{2}^{2}u\mathrm{d}t\\
 & =\left(q_{1}+\dfrac{1}{2}q_{2}^{2}\right)u\mathrm{d}t+q_{2}u\mathrm{d}W_{t},
\end{align*}
entonces, 
\begin{align*}
q_{2} & =\sigma\\
q_{1}+\dfrac{1}{2}\sigma^{2} & =\mu,
\end{align*}

entonces 
$$
Y_{t}=Y\left(0\right)\exp\left(\mu t+\sigma W_{t}\right)
$$





::: {#exr-1}

Considere la siguiente ecuación diferencial estocástica lineal. 
$$
\mathrm{d}S\left(t\right)=\left(a_{1}\mathrm{S}\left(t\right)+a_{2}\right)\mathrm{d}t+g\left(S\left(t\right)\right)\mathrm{d}W\left(t\right),
$$

donde $g:\mathbb{R}\to\mathbb{R}$ es cualquier función global de
Lipschitz con crecimiento lineal, y $a_{1},a_{2}$ son dos constantes
diferentes de cero. Use la forma integral de la ecuación diferencial
estocástica, la propiedad de martingala de la integral de Ito y la
notación 
$$
m\left(t\right)=E\left[X_{t}\right],
$$
para deducir que 
$$
m\left(t\right)-m\left(0\right)=a_{1}\int_{0}^{t}m\left(s\right)\mathrm{d}s+a_{2}t
$$

Usando que $m\left(t\right)$ es la solución 
$$
\dfrac{\mathrm{d}m\left(t\right)}{\mathrm{d}t}=a_{1}m\left(t\right)+a_{2},m\left(0\right)=E\left[X_{0}\right]
$$

Finalmente, muestre que 
$$
E\left[X\left(t\right)\right]=-\dfrac{a_{2}}{a_{1}}+\left(E\left[X\left(0\right)\right]+\dfrac{a_{2}}{a_{1}}\right)\exp\left(a_{1}t\right)
$$

:::


Primero. Considerando la formula Integral. 

\begin{align*}
S\left(t\right) & =S\left(0\right)+\int_{0}^{t}\left(a_{1}\mathrm{S}\left(t\right)+a_{2}\right)\mathrm{d}t+\int_{0}^{t}g\left(S\left(s\right)\right)\mathrm{d}W\left(s\right)\\
 & =S\left(0\right)+a_{1}\int_{0}^{t}\mathrm{S}\left(t\right)\mathrm{d}t+a_{2}t+\int_{0}^{t}g\left(S\left(s\right)\right)\mathrm{d}W\left(s\right),
\end{align*}

calculamos la esperanza. 
\begin{align*}
m\left(t\right) & =m\left(0\right)+a_{1}\int_{0}^{t}m\left(t\right)\mathrm{d}t+a_{2}t+\int_{0}^{t}E\left[g\left(S\left(s\right)\right)\right]\mathrm{d}B\left(s\right)\\
m\left(t\right)-m\left(0\right) & =a_{1}\int_{0}^{t}m\left(t\right)\mathrm{d}t+a_{2}t+E\left[\int_{0}^{t}g\left(S\left(s\right)\right)\mathrm{d}B\left(s\right)\right]
\end{align*}

Como $g$ es de lipschitz y con crecimiento lineal $g\left(S\right)\in L_{\text{ad}}^{2}\left(\Omega_{a}^{b}\right),$
por lo tanto existe una constante $c$ tal que 
$$
E\left[\int_{0}^{t}g\left(S\left(s\right)\right)\mathrm{d}W\left(s\right)\right]=c,\ \forall t
$$

Luego, sabemos que 
$$
\int_{0}^{t}g\left(S\left(s\right)\right)\mathrm{d}W\left(s\right)=\lim_{n\to\infty}\sum_{i=1}^{n}g\left(S\left(t_{i-1}\right)\right)\left(B_{i}-B_{i-1}\right),
$$

ahora, para cada $i$ 
\begin{align*}
E\left[g\left(S\left(t_{i-1}\right)\right)\left(B_{i}-B_{i-1}\right)\right] & =E\left[E\left[g\left(S\left(t_{i-1}\right)\right)\left(B_{i}-B_{i-1}\right)\mid\mathcal{F}_{i-1}\right]\right]\\
 & =E\left[g\left(S\left(t_{i-1}\right)\right)E\left[\left(B_{i}-B_{i-1}\right)\mid\mathcal{F}_{i-1}\right]\right]\\
 & =0,
\end{align*}

por lo tanto 
$$
m\left(t\right)-m\left(0\right)=a_{1}\int_{0}^{t}m\left(t\right)\mathrm{d}t+a_{2}t,
$$

ahora, considere su forma diferencial. 
$$
\dfrac{\mathrm{d}m\left(t\right)}{\mathrm{d}t}=a_{1}m\left(t\right)+a_{2},
$$

es una ecuación diferencial lineal. Por lo tanto usaremos métodos
conocidos para resolverla. 
$$
\dfrac{\mathrm{d}m\left(t\right)}{\mathrm{d}t}-a_{1}m\left(t\right)=a_{2},
$$
defina 
\begin{align*}
u & =\exp\left(\int a_{1}\mathrm{d}t\right)\\
 & =e^{-a_{1}t},
\end{align*}

\begin{align*}
\dfrac{\mathrm{d}}{\mathrm{d}t}\left[um\left(t\right)\right] & =a_{2}u\\
u\left(t\right)m\left(t\right) & =a_{2}\int u\left(t\right)\mathrm{d}t\\
m\left(t\right) & =\dfrac{a_{2}}{u\left(t\right)}\int u\left(t\right)\mathrm{d}t\\
 & =a_{2}e^{a_{1}t}\int e^{-a_{1}t}\mathrm{d}t\\
 & =-a_{2}e^{a_{1}t}\left[-\dfrac{1}{a_{1}}e^{-a_{1}t}+C\right]\\
m\left(t\right) & =-\dfrac{a_{2}}{a_{1}}-Ca_{2}e^{a_{1}t}
\end{align*}

Ahora, recordando la condición inicial. 
\begin{align*}
m\left(0\right) & =-\dfrac{a_{2}}{a_{1}}-Ca_{2}\\
\Rightarrow C & =-\dfrac{1}{a_{1}}-\dfrac{1}{a_{2}}m\left(0\right).
\end{align*}

Entonces 
$$
E\left[X_{t}\right]=-\dfrac{a_{2}}{a_{1}}-\left[-\dfrac{a_{2}}{a_{1}}-E\left[X_{0}\right]\right]\exp\left(a_{1}t\right)
$$


::: {#exr-1}

Considere la siguiente ecuación diferencial estocástica lineal. 
$$
\mathrm{d}S\left(t\right)=\left(\alpha\left(t\right)\mathrm{S}\left(t\right)\right)\mathrm{d}t+\beta\left(t\right)S\left(t\right)\mathrm{d}W\left(t\right),S\left(0\right)=s_{0},
$$

con constantes $s_{0}$ y funciones $\alpha,\beta$ integrables. Use
la formula de Ito con la fórmula 
$$
u\left(t,x\right)=\ln\left(\dfrac{x}{S_{0}}\right),
$$
para deducir que 
$$
S\left(t\right)=S\left(0\right)\exp\left(\int_{0}^{t}\left[\alpha\left(s\right)-\dfrac{1}{2}\beta^{2}\left(s\right)\right]\mathrm{d}s+\int_{0}^{t}\beta\left(s\right)\mathrm{d}W\left(s\right)\right)
$$

:::


Ahora considere que 
\begin{align*}
f\left(t\right) & =\beta\left(t\right)S\left(t\right)\\
g\left(t\right) & =\alpha\left(t\right)S\left(t\right),
\end{align*}

Calculamos las parciales de $u$. 
\begin{align*}
u_{t} & =0\\
u_{x} & =\dfrac{1}{x}\\
u_{xx} & =-\dfrac{1}{x^{2}}
\end{align*}

Entonces 
\begin{align*}
\mathrm{d}u\left(t,S_{t}\right) & =\alpha\left(t\right)\mathrm{d}t+\beta\left(t\right)\mathrm{d}W\left(t\right)-\dfrac{1}{2S_{t}^{2}}\left(dS_{t}\right)^{2}\\
 & =\alpha\left(t\right)\mathrm{d}t+\beta\left(t\right)\mathrm{d}W\left(t\right)-\dfrac{1}{2S_{t}^{2}}\beta^{2}S_{t}^{2}\mathrm{d}t\\
 & =\left[\alpha\left(t\right)-\dfrac{\beta^{2}\left(t\right)}{2}\right]\mathrm{d}t+\beta\left(t\right)\mathrm{d}W\left(t\right),
\end{align*}

entonces 
\begin{align*}
\ln\left(\dfrac{S_{t}}{S_{0}}\right) & =\int_{0}^{t}\left[\alpha\left(t\right)-\dfrac{\beta^{2}\left(t\right)}{2}\right]\mathrm{d}t+\int_{0}^{t}\beta\left(t\right)\mathrm{d}W\left(t\right)\\
S_{t} & =S_{0}\exp\left(\int_{0}^{t}\left[\alpha\left(t\right)-\dfrac{\beta^{2}\left(t\right)}{2}\right]\mathrm{d}t+\int_{0}^{t}\beta\left(t\right)\mathrm{d}W\left(t\right)\right)
\end{align*}



::: {#exr-1}

Considere la siguiente ecuación diferencial estocástica lineal. 
$$
\mathrm{d}S\left(t\right)=\left(\alpha\left(t\right)\mathrm{S}\left(t\right)\right)\mathrm{d}t+\beta\left(t\right)S\left(t\right)\mathrm{d}W\left(t\right),S\left(0\right)=s_{0},
$$

con constantes $s_{0}$ y funciones $\alpha,\beta$ integrables. Considere
\begin{align*}
\alpha\left(t\right) & =\sin\left(t\right)\\
\beta\left(t\right) & =\dfrac{t}{1+t}\\
s_{0} & =1,
\end{align*}
sobre el intervalo $\left[0,5\right]$. 

Usando el acercamiento apropiado, la salida del código reproduce 200
realizaciones de la solución con el proceso de Euler-Maruyama. 

Adapta el código para obtener la media de la solución de 1000 realizaciones
y comparalo con la media de la solución de la forma diferencial, usando
los mismos parámetros. Ilustra la diferencia con un log-plot de 

$$
\ln\left|S\left(t\right)-\tilde{S}\left(t\right)\right|,
$$

donde $S$ es la solución de Euler y $\tilde{S}$ es la solución de
la diferencial.

:::

```{python}
import numpy as np
import matplotlib.pyplot as plt
from PythonScripts import brownian_motion as bw

def alpha(t):
    y = np.sin(t)
    return y
def beta(t):
    y = t / (1.0 + t)
    return y

def drift(t, x):
    a = alpha(t) * x
    return a

def diffusion(t, x):
    b = beta(t) * x
    return b

samples = 200
sigma = 2 ** (-2)
n_p = 2 ** 8
T = 5.0
x_0 = 1.0

def get_em_solution(x_0, T, N, sigma):
    x_t = np.zeros(N)
    x_t[0] = x_0
    dt = T / N
    t, W = bw.u(T, N)
    for i in np.arange(N - 1):
        w_inc = W[i + 1] - W[i]
        f = drift(t[i], x_t[i])
        g = diffusion(t[i], x_t[i])
        x_t[i + 1] = x_t[i] + f * dt + sigma * g * w_inc  # Importante la sigma.
    return t, x_t

fig, ax = plt.subplots()
df = []
for k in np.arange(samples):
    t, x_t = get_em_solution(x_0, T, n_p, sigma)
    df.append(x_t)
    # df.append([t, x_t])
    ax.plot(t, x_t, color="C0", alpha=0.1)
plt.show()


## Analitico

s_0 = x_0

def u(t, sigma):
    y = alpha(t) - 0.5 * (sigma * beta(t)) ** 2
    return y
def v(t,sigma):
    y = sigma * beta(t)
    return y

def ito_n(n_points: int, t: float, sigma: float):
    time, w = bw.u(t, n_points)
    integral = np.zeros(n_points)
    for i in range(n_points - 1):
        integral[i] = v(time[i], sigma) * (w[i + 1] - w[i])
    ito = integral.sum()
    return ito


def riemann_integral(a, b, n_points, sigma):
    r = np.zeros(n_points)
    time = np.linspace(a,b,n_points)
    for i in range(n_points - 1):
        r[i] = u(time[i], sigma) * (time[i + 1] - time[i])
    riemann = r.sum()
    return riemann

def St(a_0,t,n_p, sigma):
    rmnn = riemann_integral(0, t, n_p, sigma)
    ito = ito_n(n_p, t, sigma) 
    y = a_0 * np.exp(rmnn + ito)
    return y

S = []
for i in range(n_p):
    S.append(St(x_0, t[i], n_p, sigma))

plt.plot(t, S)
plt.show()

# Simulado EM

em_solutions = np.array(df)

em_mean = em_solutions.mean(axis = 0)
# Simulado, Solucion General.

general_estimation = np.zeros((samples, n_p))

for i in range(samples):
    for j in range(n_p):
        general_estimation[i, j] = St(x_0, t[j], n_p, sigma)

general_mean = general_estimation.mean(axis = 0)

# 
plt.plot(t, em_mean, 'r')
plt.plot(t, general_mean, 'b', alpha = 0.5)
plt.legend(['Euler-Maruyama','Integral de Ito'])
plt.show()


## 
plt.loglog(t, np.abs(em_mean - general_mean))
plt.title("Grafica Log-Plot de |EM(t) - G(t)|")
plt.show()

```

