# Tarea 2

Sea $X_{i}$ v.a.i.i.d tales que 

$$
\mathcal{P}\left[X_{i}=h\right]=\mathcal{P}\left[X_{i}=-h\right]=\dfrac{1}{2},\forall i,
$$

entonces definimos $Y_{n,h}$.
::: 
Queremos calcular la función característica de $Y_{n,\delta}$. 

$$
E\left[i\lambda Y_{n,\delta}\left(t\right)\right],
$$

Aprovechando que para cada $X_{i}$ son v.a.i.i.d. Entonces, tenemos
lo siguiente


\begin{align*}
E\left[i\lambda Y_{n,\delta}\left(t\right)\right] & =\left(\cos\left(\lambda h\right)\right)^{t/\delta}\\
 & =u^{t},
\end{align*}

donde 
\begin{align*}
u & =\left[\cos\left(\lambda h\right)\right]^{1/\delta}\\
\ln\left(u\right) & =\dfrac{1}{\delta}\ln\left[\cos\left(\lambda h\right)\right]
\end{align*}


Entonces, aproximaremos $\cos\left(\lambda h\right)$ con su expansión
de Taylor. 
$$
\cos\left(\lambda h\right)\approx1-\dfrac{\left(\lambda h\right)^{2}}{2!}+\dfrac{\left(\lambda h\right)^{4}}{4!},
$$

entonces 
\begin{align*}
\ln\left(\cos\left(\lambda h\right)\right) & \approx\ln\left[1-\dfrac{\left(\lambda h\right)^{2}}{2}+\dfrac{\left(\lambda h\right)^{4}}{4!}\right]\\
 & \approx-\dfrac{\left(\lambda h\right)^{2}}{2!}+\dfrac{\left(\lambda h\right)^{4}}{4!}
\end{align*}

Entonces 
\begin{align*}
u^{t} & \approx\exp\left[\dfrac{t}{\delta}\left(-\dfrac{\left(\lambda h\right)^{2}}{2!}+\dfrac{\left(\lambda h\right)^{4}}{4!}\right)\right],\\
 & \approx\exp\left[-\dfrac{t}{\delta}\left(\dfrac{\lambda^{2}h^{2}}{2}-\dfrac{\lambda^{4}h^{4}}{24}\right)\right],
\end{align*}

Calculando el limite 
$$
\lim_{\delta\to0}E\left[\exp\left(i\lambda Y_{n,\delta}\left(t\right)\right)\right]=\lim_{\delta\to0}\exp\left[-t\left(\left[\dfrac{h^{2}}{\delta}\right]\left(\dfrac{\lambda^{2}}{2}-\dfrac{\lambda^{4}h^{2}}{24}\right)\right)\right],
$$

si $h^{2}/\delta\to\infty$ Segun la sucesión $\delta_{n}\to0$ tenemos
limites diferentes, por lo tanto, este no existe. Ahora, usando la
normalización, retomando las operaciones anteriores, 

\begin{align*}
E\left[\exp\left(i\lambda Y_{n,\delta}\left(t\right)+\dfrac{th^{2}\lambda^{2}}{2}\right)\right] & =E\left[\exp\left(i\lambda\sum_{i=0}^{n}X_{i}+\dfrac{th^{2}\lambda^{2}}{2\delta}\right)\right]\\
 & =E\left[\exp\left(i\lambda\sum_{i=0}^{n}X_{i}\right)\right]\exp\left(\dfrac{th^{2}\lambda^{2}}{2\delta}\right)\\
 & =\left(\left[\cos\left(\lambda h\right)\right]^{1/\delta}\exp\left(\dfrac{h^{2}\lambda^{2}}{2\delta}\right)\right)^{t},
\end{align*}

entonces, 
\begin{align*}
v & =\left[\cos\left(\lambda h\right)\right]^{1/\delta}\exp\left(\dfrac{h^{2}\lambda^{2}}{2}\right)\\
\ln v & =\ln\left[\left[\cos\left(\lambda h\right)\right]^{1/\delta}\exp\left(\dfrac{h^{2}\lambda^{2}}{2}\right)\right]\\
 & =\dfrac{1}{\delta}\ln\left[\cos\left(\lambda h\right)\right]+\dfrac{h^{2}\lambda^{2}}{2\delta}\\
 & =\dfrac{1}{\delta}\left(\ln\left[\cos\left(\lambda h\right)\right]+\dfrac{h^{2}\lambda^{2}}{2}\right)\\
 & \approx\dfrac{1}{\delta}\left(\ln\left[1\underbrace{-\dfrac{\left(\lambda h\right)^{2}}{2}+\dfrac{\left(\lambda h\right)^{4}}{4!}}_{x_{0}}\right]+\dfrac{h^{2}\lambda^{2}}{2}\right)
\end{align*}

recordando que 
$$
\ln\left(1+x\right)\approx x-\dfrac{x^{2}}{2},
$$

entonces 

$$
\ln v\approx\dfrac{1}{\delta}\left(\left[-\dfrac{\left(\lambda h\right)^{2}}{2}+\dfrac{\left(\lambda h\right)^{4}}{4!}-\dfrac{\left(-\dfrac{\left(\lambda h\right)^{2}}{2}+\dfrac{\left(\lambda h\right)^{4}}{4!}\right)^{2}}{2}\right]+\dfrac{h^{2}\lambda^{2}}{2}\right),
$$

bajo la simplificación de que $o\left(h^{k}\right)\equiv0,k\geq4,$
entonces 
\begin{align*}
\ln v & \approx\dfrac{1}{\delta}\left(\dfrac{\left(\lambda h\right)^{4}}{24}-\dfrac{\left(\lambda h\right)^{4}}{8}\right)\\
 & \approx\dfrac{1}{\delta}\left(\dfrac{\left(\lambda h\right)^{4}}{24}-\dfrac{3\left(\lambda h\right)^{4}}{24}\right)\\
v & \approx\exp\left(-\dfrac{\left(\lambda h\right)^{4}}{12\delta}\right)
\end{align*}

por lo tanto, si $h^{4}/\delta\to0$ 
$$
\lim_{\delta\to0}E\left[\exp\left(i\lambda Y_{n,\delta}\left(t\right)+\dfrac{th^{2}\lambda^{2}}{2}\right)\right]=\lim_{\delta\to0}\exp\left(-\dfrac{\left(\lambda h\right)^{4}}{12\delta}\right)=1
$$
 

