\newcommand{\DEF}{:=}
\newcommand{\D}{\mathrm{D}}
\newcommand{\R}{\mathbb{R}}


# Tarea 5
::: {#exr-1}
Muestre que el movimiento Browniano satisface 
$$
E\left[\left|W\left(t\right)-W\left(s\right)\right|^{2}\right]=\left|t-s\right|
$$

:::

Si $t>s$. 
\begin{align*}
E\left[\left|W\left(t\right)-W\left(s\right)\right|^{2}\right] & =E\left[\left(W\left(t\right)-W\left(s\right)\right)^{2}\right]\\
 & =t-s,
\end{align*}

mientras que si $t\leq s$. 
\begin{align*}
E\left[\left(W\left(t\right)-W\left(s\right)\right)^{2}\right] & =E\left[\left(W\left(s\right)-W\left(t\right)\right)^{2}\right]\\
 & =s-t,
\end{align*}

por lo tanto 
$$
E\left[\left|W\left(t\right)-W\left(s\right)\right|^{2}\right]=\left|t-s\right|
$$


::: {#exr-1}

Dado $W\left(t_{i}\right)$ y $W\left(t_{i+1}\right)$, muestre que
la variable aleatoria 
$$
W\left(t_{i+\frac{1}{2}}\right)\DEF\dfrac{1}{2}\left[W\left(t_{i}\right)+W\left(t_{i+1}\right)\right]+\dfrac{1}{2}\sqrt{\Delta t}\xi,\xi\sim N\left(0,1\right)
$$
es un movimiento Browniano.

:::

##### Es claro que al ser un refinamiento del movimiento browniano. 

$$
W\left(0\right)=0
$$


##### $C_{2}$. Notemos que 
$$
W_{i+\frac{i}{2}}-W_{i}=\dfrac{1}{2}\left[W\left(t_{i+1}\right)-W\left(t_{i}\right)\right]+\dfrac{1}{2}\sqrt{\Delta t}\xi,
$$


Sabemos que la combinación lineal de normales es una nornal. Luego,
partiendo que $t_{i+1}-t_{i}=\Delta t$.
\begin{align*}
E\left[W_{i+\frac{i}{2}}-W_{i}\right] & =0,\\
\text{Var}\left[W_{i+\frac{i}{2}}-W_{i}\right] & =\dfrac{1}{4}\Delta t+\dfrac{1}{4}\Delta t=\dfrac{1}{2}\Delta t,
\end{align*}

Por lo tanto $W_{i+\frac{1}{2}}-W_{i}\sim N\left(0,\dfrac{\Delta t}{2}\right)$. 

##### Calculamos la esperanza.

$$
E\left[\left(W_{i+1}-W_{i+\frac{1}{2}}\right)\left(W_{j+1}-W_{j+\frac{1}{2}}\right)\right]=E\left[\left(\dfrac{1}{2}\left[W\left(t_{i+1}\right)-W\left(t_{i}\right)\right]+\sqrt{\dfrac{\Delta t}{4}}\xi\right)\dfrac{1}{2}\left[W\left(t_{j+1}\right)-W\left(t_{j}\right)\right]+\sqrt{\dfrac{\Delta t}{4}}\xi\right],
$$

defina $dW_{i}=W_{i+1}-W_{i},$

\begin{align*}
E\left[\left(W_{i+1}-W_{i+\frac{1}{2}}\right)\left(W_{j+1}-W_{j+\frac{1}{2}}\right)\right] & =E\left[\left(\dfrac{1}{2}dW_{i}+\sqrt{\dfrac{\Delta t}{4}}\xi\right)\left(\dfrac{1}{2}dW_{j}+\sqrt{\dfrac{\Delta t}{4}}\xi\right)\right]\\
 & =E\left[\dfrac{1}{4}dW_{i}dW_{j}+\dfrac{1}{2}dW_{i}\sqrt{\dfrac{\Delta t}{4}}\xi+\dfrac{1}{2}dW_{j}\sqrt{\dfrac{\Delta t}{4}}\xi+\left(\sqrt{\dfrac{\Delta t}{4}}\xi\right)^{2}\right]\\
dW_{i},dW_{j}\text{ son independientes} & =\left(E\left[\dfrac{1}{2}dW_{i}\right]\right)\left(E\left[\dfrac{1}{2}dW_{j}\right]\right)+E\left[\dfrac{1}{2}dW_{i}\right]\sqrt{\dfrac{\Delta t}{4}}E\left[\xi\right]\\
 & +E\left[\dfrac{1}{2}dW_{j}\right]\sqrt{\dfrac{\Delta t}{4}}E\left[\xi\right]+\dfrac{\Delta t}{4}\left(E\left[\xi\right]\right)^{2}\\
 & =\left(E\left[\dfrac{1}{2}dW_{i}\right]\right)\left(E\left[\dfrac{1}{2}dW_{j}+\sqrt{\dfrac{\Delta t}{4}}\xi\right]\right)+E\left[\dfrac{1}{2}dW_{j}\right]\sqrt{\dfrac{\Delta t}{4}}E\left[\xi\right]+\dfrac{\Delta t}{4}\left(E\left[\xi\right]\right)^{2}\\
 & =\left(E\left[\dfrac{1}{2}dW_{i}\right]\right)\left(E\left[\left(W_{j+1}-W_{j+\frac{1}{2}}\right)\right]\right)+E\left[\dfrac{1}{2}dW_{j}\right]\sqrt{\dfrac{\Delta t}{4}}E\left[\xi\right]+\dfrac{\Delta t}{4}\left(E\left[\xi\right]\right)^{2}\\
 & =\left(E\left[\dfrac{1}{2}dW_{i}\right]\right)\left(E\left[\left(W_{j+1}-W_{j+\frac{1}{2}}\right)\right]\right)+E\left[\dfrac{1}{2}dW_{j}+\sqrt{\dfrac{\Delta t}{4}}\xi\right]\sqrt{\dfrac{\Delta t}{4}}E\left[\xi\right]\\
 & =\left(E\left[\dfrac{1}{2}dW_{i}\right]\right)\left(E\left[\left(W_{j+1}-W_{j+\frac{1}{2}}\right)\right]\right)+E\left[\left(W_{j+1}-W_{j+\frac{1}{2}}\right)\right]\sqrt{\dfrac{\Delta t}{4}}E\left[\xi\right]\\
 & =E\left[\left(W_{i+1}-W_{i+\frac{1}{2}}\right)\right]E\left[\left(W_{j+1}-W_{j+\frac{1}{2}}\right)\right],
\end{align*}
teniendo asi, que los incrementos son independientes. 

::: {#exr-1}
Generalice la fórmula del ejercicio anterior para en el caso donde,
$W\left(t_{i}\right),W\left(t_{i+1}\right),$ y $\alpha\in\left(0,1\right)$
el valor 
$$
W\left(t_{i}+\alpha\Delta t\right),
$$

es un movimiento Browniano. 
:::

Notemos que 
$$
t_{i}+\alpha\Delta t+\left(1-\alpha\right)\Delta t=t_{i+1},
$$
 entonces vamos a definir 
\begin{align*}
W_{i+\alpha} & =W\left(t_{i}+\alpha\Delta t\right)\\
 & =\left(1-\alpha\right)W_{i}+\alpha W_{i+1}+Y,
\end{align*}
donde $Y$ será una v.a independiente de $W\left(t\right)$. Entonces
\begin{align*}
W_{i+\alpha}-W_{i} & =\left(1-\alpha\right)W_{i}+\alpha W_{i+1}+Y-W_{i}\\
 & =\alpha\left(W_{i+1}-W_{i}\right)+Y\\
 & =\alpha\left(W_{i+1}-W_{i}\right)+Y.
\end{align*}

Entonces 
$$
E\left[W_{i+\alpha}-W_{i}\right]=E\left[Y\right],
$$

por lo tanto, $E\left[Y\right]$ tiene que ser cero. Luego 
$$
\text{Var}\left[W_{i+\alpha}-W_{i}\right]=\alpha^{2}\Delta t+\text{Var}\left[Y\right],
$$

notemos que 
$$
\left(i+\alpha\right)\Delta t-i\Delta t=\alpha\Delta t,
$$

por lo tanto tendría que cumplirse $\text{Var}\left[W_{i+\alpha}-W_{i}\right]=\alpha\Delta t$. 

$$
\alpha^{2}\Delta t+\text{Var}\left[Y\right]=\alpha\Delta t,
$$

entonces 
$$
\text{Var}\left[Y\right]=\Delta t\left(\alpha-\alpha^{2}\right),
$$

como $Y=\sqrt{\alpha\left(1-\alpha\right)}\xi,\xi\sim N\left(0,1\right)$. Como este es un refinamiento del browniano, entonces se cumple $C1$.
$$
W\left(0\right)=0.
$$

Conseguimos $C2$ por construcción y de forma análoga tenemos la independiencia
de los incrementos. 
$$
E\left[\left(W_{i+\alpha}-W_{i}\right)\left(W_{j+\alpha}-W_{j}\right)\right]=E\left[W_{i+\alpha}-W_{i}\right]E\left[W_{j+\alpha}-W_{j}\right].
$$


::: {#exr-1}
Suponga que $X\sim N\left(0,1\right)$. Sabemos que $E\left[X\right]=0$
y $E\left[X^{2}\right]=3$. Luego, de la definición, el $p-$ ésimo
momento satisface 
$$
E\left[X^{p}\right]=\dfrac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}x^{p}\exp\left(-\frac{x^{2}}{2}\right)\D x.
$$

Usando la relación, muestre que $E\left[X^{3}\right]=0$ y $E\left[X^{4}\right]=1$.

Entonces deduzca el incremento Browniano, 
$$
\Delta W_{i}=W\left(t_{i+1}\right)-W\left(t_{i}\right),
$$

satisface $E\left[\Delta W_{i}^{3}\right]=0,E\left[\Delta W_{i}^{4}\right]=3\left(\Delta t\right)^{2}$.
Entonces encuentre una expresión para $E\left[X^{p}\right]$ para
un entero positivo $p$.\\
Pista: Tu puedes usar el dato que $\int_{-\infty}^{\infty}\exp\left(-\dfrac{x^{2}}{2}\right)=\sqrt{2\pi}.$
:::

Considere la fórmula. 
$$
E\left[X^{p}\right]=\dfrac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}x^{p}\exp\left(-\frac{x^{2}}{2}\right)\D x.
$$

Partiendo la integral, 
$$
\dfrac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}x^{p}\exp\left(-\frac{x^{2}}{2}\right)\D x=\underbrace{\dfrac{1}{\sqrt{2\pi}}\int_{-\infty}^{0}x^{p}\exp\left(-\frac{x^{2}}{2}\right)\D x}_{I_{1}}+\underbrace{\dfrac{1}{\sqrt{2\pi}}\int_{0}^{\infty}x^{p}\exp\left(-\frac{x^{2}}{2}\right)\D x}_{I_{2}}
$$

Entonces 
$$
I_{1}=\dfrac{1}{\sqrt{2\pi}}\int_{-\infty}^{0}x^{p}\exp\left(-\dfrac{x^{2}}{2}\right)\D x,
$$

hagamos el cambio de variable. $y=-x,$ tenemos que 
\begin{align*}
I_{1} & =\dfrac{1}{\sqrt{2\pi}}\int_{\infty}^{0}-\left(-y\right)^{p}\exp\left(-\dfrac{y^{2}}{2}\right)\D y\\
 & =\dfrac{\left(-1\right)^{p}}{\sqrt{2\pi}}\int_{0}^{\infty}y^{p}\exp\left(-\dfrac{y^{2}}{2}\right)\D y=I_{2}\left(-1\right)^{p},
\end{align*}
entonces 
$$
E\left[X^{p}\right]=\left(1+\left(-1\right)^{p}\right)I_{2},
$$

de aqui tenemos, que si $p$ es impar $E\left[X^{p}\right]=0,$ entonces si $p$ es par 
$$
E\left[X^{p}\right]=2I_{2},
$$

entonces, nos concentraremos en 
$$
E\left[X^{p}\right]=\dfrac{2}{\sqrt{2\pi}}\int_{0}^{\infty}x^{p}\exp\left(-\frac{x^{2}}{2}\right)\D x,p=2k,k\in\mathbb{N}
$$

Considere $y=\dfrac{x^{2}}{2},\D y=x\D x$.

$$
E\left[X^{p}\right]=\dfrac{2}{\sqrt{2\pi}}\int_{0}^{\infty}x^{p-1}\exp\left(-y\right)\D y,
$$

luego $\sqrt{2y}=x,$ entonces 
\begin{align*}
E\left[X^{p}\right] & =\dfrac{2}{\sqrt{2\pi}}\int_{0}^{\infty}\left(\sqrt{2y}\right)^{p-1}\exp\left(-y\right)\D y\\
 & =\dfrac{2\left(\sqrt{2}\right)^{p-1}}{\sqrt{2\pi}}\int_{0}^{\infty}y^{\frac{p-1}{2}}\exp\left(-y\right)\D y\\
 & =\dfrac{2\left(\sqrt{2}\right)^{p-1}}{\sqrt{2\pi}}\int_{0}^{\infty}y^{\frac{p+1}{2}-1}\exp\left(-y\right)\D y,
\end{align*}
recordando la función Gamma. 
$$
\Gamma\left(z\right)=\int_{0}^{\infty}x^{z-1}e^{-t}\D t,
$$

entonces 

$$
E\left[X^{p}\right]=\begin{cases}
0 & p\text{ impar}\\
\dfrac{2^{\frac{p+1}{2}}}{\sqrt{2\pi}}\Gamma\left(\dfrac{p+1}{2}\right) & p\text{ par}
\end{cases},
$$

entonces $E\left[X^{4}\right]=\dfrac{4}{\sqrt{\pi}}\Gamma\left(\dfrac{5}{2}\right)$

\begin{align*}
\Gamma\left(\dfrac{5}{2}\right) & =\int_{0}^{\infty}x^{\frac{3}{2}}e^{-x}\D x.
\end{align*}

Considere 
\begin{align*}
u=x^{3/2} & \D v=e^{-x}\D x\\
\D u=\dfrac{3}{2}x^{1/2} & v=-e^{-x},
\end{align*}

\begin{align*}
\Gamma\left(\dfrac{5}{2}\right) & =\left[-x^{3/2}e^{-x}\right]+\dfrac{3}{2}\int_{0}^{\infty}x^{1/2}e^{-x}\D x\\
 & =\dfrac{3}{2}\dfrac{\sqrt{\pi}}{2}.
\end{align*}

Entonces 
$$
E\left[X^{4}\right]=3
$$

Notemos que si $\Delta W\sim N\left(0,\sigma^{2}\right)$, entonces
$$
Z=\dfrac{\Delta W}{\sigma}\sim N\left(0,1\right)
$$

En general, 
$$
E\left[\left(\Delta W\right)^{p}\right]=\dfrac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}w^{p}\exp\left(-\left(\dfrac{w}{\sigma}\right)^{2}\right)\D w,
$$

considere $\sigma u=w$, entonces 
\begin{align*}
E\left[\left(\Delta W\right)^{p}\right] & =\sigma^{p}\left[\dfrac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}u^{p}\exp\left(-u^{2}\right)\D w\right],\\
 & =\sigma^{p}E\left[Z^{p}\right],
\end{align*}

entonces para $p=4,\sigma^{2}=\Delta t$. 
$$
E\left[\left(\Delta W\right)^{4}\right]=\left(\Delta t\right)^{2}E\left[Z^{4}\right]=3\left(\Delta t\right)^{2}
$$


::: {#exr-1}
Suponga que $X\sim N\left(0,1\right)$. Muestre que para $a,b\in\R$,
$$
E\left[\exp\left(a+bX\right)\right]=\exp\left(a+\dfrac{1}{2}b^{2}\right).
$$
Deduzca que 
$$
E\left[\exp\left(t+\dfrac{1}{4}W_{t}\right)\right]=\exp\left(\dfrac{33}{32}t\right)
$$

:::

Considere 
$$
E\left[\exp\left(a+bX\right)\right]=e^{a}E\left[\exp\left(bX\right)\right],
$$

notemos que $bX\sim N\left(0,b^{2}\right),$ por lo tanto, la función
generadora de momentos nos dice que 
$$
E\left[\exp\left(bX\right)\right]=M_{bX}\left(1\right)=\exp\left(\dfrac{b^{2}}{2}\right),
$$

por lo tanto 
$$
E\left[\exp\left(a+bX\right)\right]=e^{a}\exp\left(\dfrac{b^{2}}{2}\right)=\exp\left(a+\dfrac{1}{2}b^{2}\right),
$$

ahora, considere 
$$
E\left[\exp\left(t+\dfrac{1}{4}W_{t}\right)\right]=E\left[\exp\left(t+\dfrac{1}{4}\left(W_{t}-W_{0}\right)\right)\right],
$$

Notemos que $W_{t}-W_{0}\sim N\left(0,t\right),$ por lo tanto, usando
la fórmula anterior 

\begin{align*}
E\left[\exp\left(t+\dfrac{1}{4}\left(W_{t}-W_{0}\right)\right)\right] & =\exp\left(t+\dfrac{1}{4}\left(\sqrt{t}X\right)\right),X\sim N\left(0,1\right)\\
 & =\exp\left(t+\left(\dfrac{1}{4}\sqrt{t}\right)X\right)=\exp\left(t+\dfrac{t}{32}\right)\\
 & =\exp\left(\dfrac{33}{32}t\right)
\end{align*}
