# Tarea 8

::: {exr-1}
Use la aproximación de la suma de Riemann la ecuación 6.1. Muestra la propiedad de linealidad de la integral estocástica. Es decir,
$$
\int_{0}^{T}\left(\alpha f(t)+\beta g(t)\right) dW_{t}=\alpha\int_{0}^{T}f(t)dW_{t}+\beta\int_{0}^{T}g(t)dW_{t}
$$

:::
Sea $\{0=t_{0},t_{1},\dots,t_{L-1},t_{L}=T\}$ una particion del intervalo $[0,T]$, de la aproximación de la suma de Riemann, resulta
\begin{eqnarray*}
    \int_{0}^{T}\left(\alpha f(t)+\beta g(t)\right) dW_{t} & \sim & \sum_{i=0}^{L}(\alpha f(t_{i})+\beta g(t_{i}))(W(t_{i+1})-W(t_{i}))\\
    & = & \sum_{i=0}^{L}\alpha f(t_{i})(W(t_{i+1})-W(t_{i}))+ \sum_{i=0}^{L}\beta g(t_{i})(W(t_{i+1})-W(t_{i}))\\
    & = & \alpha\sum_{i=0}^{L} f(t_{i})(W(t_{i+1})-W(t_{i}))+\beta\sum_{i=0}^{L} g(t_{i})(W(t_{i+1})-W(t_{i}))
\end{eqnarray*}

tomando el limite cuando $L\to\infty$, resulta
$$
    \alpha\lim_{L\to\infty}\sum_{i=0}^{L} f(t_{i})(W(t_{i+1})-W(t_{i}))=\alpha \int_{0}^{T}f(t)dW_{t}
$$

y
$$
    \beta\lim_{L\to\infty}\sum_{i=0}^{L} g(t_{i})(W(t_{i+1})-W(t_{i}))=\beta\int_{0}^{T}g(t)dW_{t}
$$

así,
$$
\int_{0}^{T}\left(\alpha f(t)+\beta g(t)\right) dW_{t}= \alpha \int_{0}^{T}f(t)dW_{t}+\beta\int_{0}^{T}g(t)dW_{t}
$$

::: {exr-1}
Escriba con detalle la demostración del siguiente Teorema, también incluya la demostración del Lema 5.18 del Mao.\\
Teorema: Sea $f\in\mathcal{M}^{2}([0,T];\mathbb{R})$, sea $\rho,\tau$ dos tiempos de paro tales que $0\leq\rho\leq\tau\leq T$. Entonces
\begin{eqnarray}
    \mathbb{E}\left(\int_{\rho}^{\tau}f(s)dW_{s}\mid\mathcal{F}_{\rho}\right) & = & 0,\\
    \mathbb{E}\left(\left|\int_{\rho}^{\tau}f(s)dW_{s}\right|^{2}\mid\mathcal{F}_{\rho}\right) & = & \mathbb{E}\left(\int_{\rho}^{\tau}\left|f(s)\right|^{2}ds\mid\mathcal{F}_{\rho}\right).
\end{eqnarray}
:::

Por el Teorema 5.14 y el teorema de paro de la martingala de Doob,
\begin{equation}
    E(I(\tau)|\mathcal{F}_{\rho})=I(\rho)
\end{equation}
y
\begin{equation}
    E(I^{2}(\tau)-\langle I,I\rangle_{\tau}|\mathcal{F}_{\rho})=I^{2}(\rho)-\langle I,I\rangle_{\rho},
\end{equation}
donde $\{\langle I,I\rangle_{t}\}$ es definido por 5.18. Aplicando el Lema 5.18 se ve entonces de 5.22 que
$$
\mathbb{E}\left(\int_{\rho}^{\tau}f(s)dB_{s}|\mathcal{F}_{\rho}\right)=\mathbb{E}(I(\tau)-I(\rho)|\mathcal{F}_{\rho})=0
$$

que es (5.20). Además, por (5.22) y (5.23),

$$
\mathbb{E}(|I(\tau)-I(\rho)|^{2}|\mathcal{F}_{\rho})=\mathbb{E}(I^{2}(\tau)|\mathcal{F}_{\rho})-2I(\rho)\mathbb{E}(I(\tau)|\mathcal{F}_{\rho})+I^{2}(\rho)
$$

$$
=\mathbb{E}(I^{2}(\tau)|\mathcal{F}_{\rho})-I^{2}(\rho)=\mathbb{E}(\langle I,I\rangle_{\tau}-\langle I, I\rangle_{\rho}|\mathcal{F}_{\rho})=\mathbb{E}\left(\int_{\rho}^{\tau}|f(s)|^{2}ds|\mathcal{F}_{\rho}\right)
$$


::: {exr-1}
Usando la aproximación de la suma de Riemann ecuación 6.1, la isometría de Itô y la identidad $4ab=(a+b)^{2}-(a-b)^{2}$ pruebe que
$$
\mathbb{E}\left[\left(\int_{0}^{T}g(t)dW_{t}\right)\left(\int_{0}^{T}f(t)dW_{t}\right)\right]=\int_{0}^{T}\mathbb{E}[f(t)g(t)]dt.
$$

:::
Tomemos $a=\int_{0}^{T}g(t)dW_{t}$ y $b=\int_{0}^{T}f(t)dW_{t}$, entonces usando la identidad $4ab=(a+b)^{2}-(a-b)^{2}$
\begin{eqnarray*}
    4\left(\int_{0}^{T}g(t)dW_{t}\right)\left(\int_{0}^{T}f(t)dW_{t}\right) & = & \left(\int_{0}^{T}g(t)dW_{t}+\int_{0}^{T}f(t)dW_{t}\right)^{2}-\left(\int_{0}^{T}g(t)dW_{t}-\int_{0}^{T}f(t)dW_{t}\right)^{2}\\
    & = & \left(\int_{0}^{T}(g(t)+f(t))dW_{t}\right)^{2}-\left(\int_{0}^{T}(g(t)-f(t))dW_{t}\right)^{2},
\end{eqnarray*}
así,
\begin{eqnarray*}
    4\mathbb{E}\left[\left(\int_{0}^{T}g(t)dW_{t}\right)\left(\int_{0}^{T}f(t)dW_{t}\right)\right] & = & \mathbb{E}\left(\int_{0}^{T}(g(t)+f(t))dW_{t}\right)^{2}-\mathbb{E}\left(\int_{0}^{T}(g(t)-f(t))dW_{t}\right)^{2}\\
   & = &\left(\int_{0}^{T} \mathbb{E}(g(t)+f(t))^{2}dt\right)-\left(\int_{0}^{T}\mathbb{E}(g(t)-f(t))^{2}dt\right)\\
    & = & \left(\int_{0}^{T}\mathbb{E}[(g(t)+f(t))^{2}-(g(t)-f(t))^{2}]dt\right)\\
    & = & 4\left(\int_{0}^{T}\mathbb{E}[g(t)f(t)]dt\right)
\end{eqnarray*}

::: {exr-1}
Usando la suma de Riemann ecuación 6.1 y deduzca que,
$$
\int_{0}^{T}W(t)^{2}dW(t)=\dfrac{1}{3}W(T)^{3}-\int_{0}^{T}W(t)dt.
$$

:::

Observemos que,
$$
3W(t_{i})^{2}(W(t_{i+1})-W((t_{i})))=W(t_{i+1})^{3}-\left(W(t_{i+1})-W(t_{i})\right)^{3}-3\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})-W(t_{i-1})^{3},
$$

aplicando la ecuación 6.1
\begin{align*}
\int_{0}^{T}W(t)^{2}dW(t) & \sim \sum_{i=0}^{L}W(t_{i})^{2} (W(t_{i+1})-W((t_{i})))\\
& = \frac{1}{3} \sum_{i=0}^{L}\left[W(t_{i+1})^{3}-W(t_{i-1})^{3}\right]-\frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}-\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})\\
 & =\frac{1}{3}( W(T)^{3}-W(t_{0})^{3})- \frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}-\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})\\
  & =\frac{1}{3}W(T)^{3}- \frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}-\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})
\end{align*}
veamos que $\frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}\to 0$ en $L^{2}$.\\
Ahora, calcularemos la media de la variación cuadrática. Del Teorema Multinomial
$$
\frac{1}{9}\mathbb{E}\left[\left(\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}\right)^{2}\right]=\frac{1}{9}\sum_{i=0}^{L}\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{6}\right]+\frac{2}{9}\sum_{i=0}^{L}\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right],
$$

además, de la tarea 5,
\begin{eqnarray*}
    \mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right] & = & \mathbb{E}\{\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right]|\mathcal{F}_{j}\}\\
    & = & \mathbb{E}\{\left(W(t_{i+1})-W(t_{i})\right)^{3}\mathbb{E}\left[\left(W(t_{j+1})-W(t_{j})\right)^{3}\right|\mathcal{F}_{j}]\}\\
    & = & \mathbb{E}[\left(W(t_{i+1})-W(t_{i})\right)^{3}]\mathbb{E}\left[\left(W(t_{j+1})-W(t_{j})\right)^{3}\right]\\
    & = & 0. \text{ de la tarea 5}
\end{eqnarray*}
así, 
$$
\frac{2}{9}\sum_{i=0}^{L}\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right]=0
$$

y también se tiene que $\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{6}\right] = 15\left(t_{i+1}-t_{i}\right)^{3}$, así
\begin{align*}
\frac{1}{9}\sum_{i=0}^{L}E\left[\left(W(t_{i+1})-W(t_{i})\right)^{6}\right] & =\frac{5}{3}\sum_{i=0}^{L}\left(t_{i+1}-t_{i}\right)^{3}\\
 & \leq\frac{5}{3}\|\Delta_{L}\|^{2}\sum_{i=0}^{L}\left(t_{i+1}-t_{i}\right)\\
 & \leq\frac{5}{3}\|\Delta_{L}\|^{2}L\to0,\|\Delta_{L}\|\to0
\end{align*}
Ahora veamos que
$$
\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})\to \sum_{i=0}^{L}W(t_{i})\left(t_{i+1}-t_{i}\right)\text{ en }L^{2}
$$

se tiene que, 
\begin{eqnarray*}
  \mathbb{E}\left[\left(\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})- \sum_{i=0}^{L}W(t_{i})\left(t_{i+1}-t_{i}\right) \right)^{2}\right] & = & \mathbb{E}\left[\left(\sum_{i=0}^{L}W(t_{i})[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)] \right)^{2}\right]
\end{eqnarray*}
$$
\mathbb{E}\left[\sum_{i=0}^{L}W(t_{i})^{2}[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)]^{2} +\sum_{i=0}^{L}W(t_{i})W(t_{j})[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)][\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right)] \right]
$$

calculemos
\begin{eqnarray*}
 \mathbb{E}\{\mathbb{E}[W(t_{i})W(t_{j})(\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right))(\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right))]|\mathcal{F}_{j}\} & = &   
\end{eqnarray*}
$$
 \mathbb{E}\{W(t_{i})W(t_{j})(\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right))\mathbb{E}[(\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right))]|\mathcal{F}_{j}\} =0
$$


::: {exr-1}
Verifique que la isometría de Itô ecuación 6.4,
$$
\mathbb{E}\left[\left(\int_{0}^{T}h(t)dW(t)\right)^{2}\right]=\mathbb{E}\left[\int_{0}^{T}h(t)^{2}dt\right],
$$

se tiene cuando $h(t):= 1$.
:::
del ejercicio 3, resulta
\begin{eqnarray*}
    \mathbb{E}\left[\left(\int_{0}^{T}h(t)dW(t)\right)^{2}\right]=\mathbb{E}\left[\left(\int_{0}^{T}1dW(t)\right)^{2}\right] & = & \mathbb{E}\left[\left(\int_{0}^{T}1dW_{t}\right)\left(\int_{0}^{T}1dW_{t}\right)\right]\\
    & = & \int_{0}^{T}\mathbb{E}[1]dt\\
    & = & \int_{0}^{T}dt\\
    & = & T.
\end{eqnarray*}
y
\begin{eqnarray*}
    \mathbb{E}\left[\int_{0}^{T}h(t)^{2}dt\right] & = & \mathbb{E}\left[\int_{0}^{T}1^{2}dt\right]\\
    & = & \mathbb{E}\left[\int_{0}^{T}dt\right]\\
    & = & \mathbb{E}\left[T\right]\\
    & = & T
\end{eqnarray*}

Así,
$$
\mathbb{E}\left[\left(\int_{0}^{T}dW(t)\right)^{2}\right]= \mathbb{E}\left[\int_{0}^{T}dt\right] 
$$
